apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/address-pool: minikube
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 20
    name: data
    protocol: TCP
    targetPort: 20
  - port: 21
    name: ftps
    protocol: TCP
    targetPort: 21
  - port: 30020
    name: ftps-pasv20
    protocol: TCP
    targetPort: 30020
  - port: 30021
    name: ftps-pasv
    protocol: TCP
    targetPort: 30021
  externalIPs:
    - "192.168.99.166"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pv
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc

